# Generated by Django 4.2.7 on 2026-01-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_duplicate_redemptions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redemptionlog',
            unique_together={('user', 'reward')},
        ),
    ]
