# Generated by Django 4.2.7 on 2026-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Rank/position (1=first, 2=second, etc.)')),
                ('username', models.CharField(max_length=100)),
                ('reward_won', models.CharField(blank=True, help_text='What they won (e.g. "Steam Key", "Discord Nitro")', max_length=200)),
                ('date_won', models.DateField(blank=True, help_text='When they won', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = higher on list)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard entries',
                'ordering': ['order', 'position', '-created_at'],
            },
        ),
    ]
